[package]
name = "comment_unorthodoxdev_net"
version = "0.1.0"
edition = "2021"

[lib]
name = "cmanager"
path = "cmanager/src/lib.rs"

[dependencies]
sqlite = "0.31.0"
uuid = {version = "1.4.1", features = ["v4"] }
