[package]
name = "comment_unorthodoxdev_net"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.8", features = [
    "mysql",
    "runtime-tokio",
    "tls-native-tls",
] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
