[package]
name = "cmanager"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "1.4.1", features = ["v4"] }
sqlite = "0.31"
chrono = "0.4.26"
sha256 = "1.2.2"

